#!/bin/sh

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C)  TinyTools

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

repos=''
ignore_regex='antigen|vim'

update() {
    repos=$(find "$HOME" -name ".git" | awk -F/ 'BEGIN { OFS = FS } NF{NF-=1};1')
    [ -n "$ignore_regex" ] && repos=$(printf '%b' "$repos" | grep -E -v "$ignore_regex")
    touch /tmp/repos.dat
    printf '%b' "$repos" > /tmp/repos.dat
}

get_repos(){
    if [ -f "/tmp/repos.dat" ]; then
        printf '%b' "$(cat "/tmp/repos.dat")"
    else
        update && printf '%b' "$(cat "/tmp/repos.dat")"
    fi
}

list() {
    for i in $repos
    do
        cd "$i" || printf "git directory not found"
        if [ "$(git rev-parse --git-dir)" = ".git" ]; then
            status=$(tgit-status "$i" "$1")
            name=$(printf '%s' "$i" | sed "s $HOME/  " )
            list="$list\n[$status] $name"
        fi
    done
    tmpfile=$(mktemp)
    printf '%b' "$list" >> "$tmpfile"
    list=$(column "$tmpfile" -t)
    rm "$tmpfile"
    printf '%b' "$list"
}

repos=$(get_repos)

while getopts uc option
do
    case "${option}" in
        u) update && exit;;
        c) printf '%b\n' "$(list -c)" && exit ;;
        *) usage; exit 1 ;;
    esac
done
printf '%b\n' "$(list)"